prefix="$(cd $(dirname "$BASH_SOURCE") && pwd)"
export PARTOCHE_ROOT="${prefix}"
export PATH="${prefix}/bin:${PATH}"
export LD_LIBRARY_PATH="${prefix}/bin:${LD_LIBRARY_PATH}"
export OCAMLPATH="${prefix}/lib/ocamlfind:${OCAMLPATH}"
